In [10]:
import polars as pl
from pathlib import Path

DATA_PATH = Path("../data/raw/qna.csv")

print("Dataset:", DATA_PATH)
print("Exists:", DATA_PATH.exists())
print("Size (GB):", round(DATA_PATH.stat().st_size / (1024**3), 2))

Dataset: ../data/raw/qna.csv
Exists: True
Size (GB): 2.64

In [11]:
df = pl.scan_csv(
    DATA_PATH,
    infer_schema_length=10_000,
    ignore_errors=False
)

df

In [12]:
schema = df.collect_schema()

print("Jumlah kolom:", len(schema))
print("\nKolom dan tipe data:")

for name, dtype in schema.items():
    print(f"- {name}: {dtype}")

Jumlah kolom: 10

Kolom dan tipe data:
- id: String
- title: String
- user: String
- question: String
- question_clean: String
- question_post_date: String
- answer_by: String
- answer_post_date: String
- answer: String
- answer_clean: String

In [13]:
row_count = (
    df
    .select(pl.len().alias("row_count"))
    .collect()
)

row_count

shape: (1, 1)
┌───────────┐
│ row_count │
│ ---       │
│ u32       │
╞═══════════╡
│ 681203    │
└───────────┘

In [14]:
columns = schema.names()

missing = (
    df
    .select([
        pl.col(column)
        .null_count()
        .alias(column)
        for column in columns
    ])
    .collect()
)

missing

shape: (1, 10)
┌─────┬───────┬──────┬──────────┬───┬───────────┬──────────────────┬────────┬──────────────┐
│ id  ┆ title ┆ user ┆ question ┆ … ┆ answer_by ┆ answer_post_date ┆ answer ┆ answer_clean │
│ --- ┆ ---   ┆ ---  ┆ ---      ┆   ┆ ---       ┆ ---              ┆ ---    ┆ ---          │
│ u32 ┆ u32   ┆ u32  ┆ u32      ┆   ┆ u32       ┆ u32              ┆ u32    ┆ u32          │
╞═════╪═══════╪══════╪══════════╪═══╪═══════════╪══════════════════╪════════╪══════════════╡
│ 0   ┆ 9     ┆ 4    ┆ 22       ┆ … ┆ 0         ┆ 0                ┆ 0      ┆ 15           │
└─────┴───────┴──────┴──────────┴───┴───────────┴──────────────────┴────────┴──────────────┘

In [15]:
missing_summary = (
    df
    .select([
        pl.col(column).null_count().alias(f"{column}_missing")
        for column in columns
    ])
    .collect()
)

missing_summary

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id_missin ┆ title_mis ┆ user_miss ┆ question_ ┆ … ┆ answer_by ┆ answer_po ┆ answer_mi ┆ answer_c │
│ g         ┆ sing      ┆ ing       ┆ missing   ┆   ┆ _missing  ┆ st_date_m ┆ ssing     ┆ lean_mis │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ issing    ┆ ---       ┆ sing     │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ ---       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ u32       ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 9         ┆ 4         ┆ 22        ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 15       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
duplicate_id = (
    df
    .group_by("id")
    .len()
    .filter(pl.col("len") > 1)
    .sort("len", descending=True)
    .collect()
)

duplicate_id.head(20)

shape: (20, 2)
┌──────────────────────────┬─────┐
│ id                       ┆ len │
│ ---                      ┆ --- │
│ str                      ┆ u32 │
╞══════════════════════════╪═════╡
│ 576affb8abcdce1d710181f5 ┆ 19  │
│ 576affb8abcdce1d710181b7 ┆ 12  │
│ 576affdbabcdce1d7101de1c ┆ 12  │
│ 576affb8abcdce1d71018471 ┆ 11  │
│ 576affb8abcdce1d710180c4 ┆ 11  │
│ …                        ┆ …   │
│ 576affb8abcdce1d7101838d ┆ 9   │
│ 576affb8abcdce1d71017f38 ┆ 9   │
│ 576affe7abcdce1d710203ab ┆ 9   │
│ 576affd0abcdce1d7101cf0d ┆ 9   │
│ 576affdbabcdce1d7101dded ┆ 9   │
└──────────────────────────┴─────┘

In [17]:
print("Jumlah ID yang duplikat:", duplicate_id.height)

Jumlah ID yang duplikat: 212182

In [18]:
text_profile = (
    df
    .select([
        pl.col("question")
        .str.len_chars()
        .alias("question_length"),

        pl.col("answer")
        .str.len_chars()
        .alias("answer_length")
    ])
    .select([
        pl.col("question_length").mean().alias("question_mean"),
        pl.col("question_length").median().alias("question_median"),
        pl.col("question_length").min().alias("question_min"),
        pl.col("question_length").max().alias("question_max"),

        pl.col("answer_length").mean().alias("answer_mean"),
        pl.col("answer_length").median().alias("answer_median"),
        pl.col("answer_length").min().alias("answer_min"),
        pl.col("answer_length").max().alias("answer_max"),
    ])
    .collect()
)

text_profile

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ question_m ┆ question_m ┆ question_m ┆ question_ ┆ answer_me ┆ answer_me ┆ answer_mi ┆ answer_ma │
│ ean        ┆ edian      ┆ in         ┆ max       ┆ an        ┆ dian      ┆ n         ┆ x         │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ u32        ┆ u32       ┆ f64       ┆ f64       ┆ u32       ┆ u32       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 364.538255 ┆ 294.0      ┆ 1          ┆ 232868    ┆ 1722.0187 ┆ 1624.0    ┆ 2         ┆ 471356    │
│            ┆            ┆            ┆           ┆ 89        ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [19]:
sample = (
    df
    .select([
        "id",
        "title",
        "question_post_date",
        "answer_post_date",
        "question",
        "answer"
    ])
    .head(5)
    .collect()
)

sample

shape: (5, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ id             ┆ title          ┆ question_post_ ┆ answer_post_d ┆ question      ┆ answer        │
│ ---            ┆ ---            ┆ date           ┆ ate           ┆ ---           ┆ ---           │
│ str            ┆ str            ┆ ---            ┆ ---           ┆ str           ┆ str           │
│                ┆                ┆ str            ┆ str           ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 64b0ea5657ecf6 ┆ Ciri-ciri      ┆ Fri Jul 14     ┆ Fri Jul 14    ┆ <p>Pandangan  ┆ <p>Alo,       │
│ 002526920e     ┆ penyakit       ┆ 2023 13:25:00  ┆ 2023 17:59:00 ┆ mata saya     ┆ terimakasih   │
│                ┆ ablasio ret…   ┆ GMT+0…         ┆ GMT+0…        ┆ udah se…      ┆ atas per…     │
│ 630c1595666c14 ┆ Apakah ablasi  ┆ Mon Aug 29     ┆ Mon Aug 29    ┆ <p>Hi dokter, ┆ <p>Selamat    │
│ 06f7a2798f     ┆ retina bisa    ┆ 2022 08:25:00  ┆ 2022 12:56:00 ┆ dok saya ada  ┆ siang, terima │
│                ┆ semb…          ┆ GMT+0…         ┆ GMT+0…        ┆ g…            ┆ kas…          │
│ 62dba6259bff74 ┆ Tindakan untuk ┆ Sat Jul 23     ┆ Sat Jul 23    ┆ <p>Alo        ┆ <p>Alo,       │
│ 07087e7fd6     ┆ mengatasi      ┆ 2022 14:41:00  ┆ 2022 16:25:00 ┆ dokter...     ┆ terimakasih   │
│                ┆ kerus…         ┆ GMT+0…         ┆ GMT+0…        ┆ Saya ingin …  ┆ atas per…     │
│ 625abb4407faa1 ┆ Apakah ablasi  ┆ Sat Apr 16     ┆ Sat Apr 16    ┆ <p>Selamat    ┆ <p>Terima     │
│ 0613bb6bf7     ┆ retina yang di ┆ 2022 19:49:00  ┆ 2022 21:06:00 ┆ malam dok,    ┆ kasih atas    │
│                ┆ s…             ┆ GMT+0…         ┆ GMT+0…        ┆ saya m…       ┆ pertany…      │
│ 6255666503dcb1 ┆ Penyebab dan   ┆ Tue Apr 12     ┆ Tue Apr 12    ┆ <p>mohon maaf ┆ <p>Alo,       │
│ 060dc9dfe9     ┆ penanganan     ┆ 2022 18:45:00  ┆ 2022 19:22:00 ┆ dok mau tanya ┆ terima kasih  │
│                ┆ ablasi…        ┆ GMT+0…         ┆ GMT+0…        ┆ …             ┆ ya suda…      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [20]:
date_sample = (
    df
    .select([
        "question_post_date",
        "answer_post_date"
    ])
    .head(20)
    .collect()
)

date_sample

shape: (20, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ question_post_date              ┆ answer_post_date                │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ Fri Jul 14 2023 13:25:00 GMT+0… ┆ Fri Jul 14 2023 17:59:00 GMT+0… │
│ Mon Aug 29 2022 08:25:00 GMT+0… ┆ Mon Aug 29 2022 12:56:00 GMT+0… │
│ Sat Jul 23 2022 14:41:00 GMT+0… ┆ Sat Jul 23 2022 16:25:00 GMT+0… │
│ Sat Apr 16 2022 19:49:00 GMT+0… ┆ Sat Apr 16 2022 21:06:00 GMT+0… │
│ Tue Apr 12 2022 18:45:00 GMT+0… ┆ Tue Apr 12 2022 19:22:00 GMT+0… │
│ …                               ┆ …                               │
│ Mon Jul 19 2021 22:12:00 GMT+0… ┆ Tue Jul 20 2021 10:55:00 GMT+0… │
│ Mon Jul 05 2021 15:56:00 GMT+0… ┆ Mon Jul 05 2021 23:24:00 GMT+0… │
│ Wed Jun 16 2021 08:18:00 GMT+0… ┆ Wed Jun 16 2021 12:23:00 GMT+0… │
│ Thu May 20 2021 14:35:00 GMT+0… ┆ Thu May 20 2021 22:08:00 GMT+0… │
│ Fri Apr 09 2021 00:24:00 GMT+0… ┆ Fri Apr 09 2021 10:27:00 GMT+0… │
└─────────────────────────────────┴─────────────────────────────────┘